### ISSUE TITLE
Throws script error?

### ISSUE THREAD

**Issue by kumaresan-subramani** [electric-eloquence/gulp4-run-sequence#3]
## Bug 

when using this package it throws below error

> D:\ej2-es-build>gulp buildw
> [18:31:45] Using gulpfile D:\ej2-es-build\gulpfile.js
> [18:31:45] Starting 'buildw'...
> [18:31:45] 'buildw' errored after 1.44 ms
> [18:31:45] TypeError: Cannot read property 'apply' of undefined
>     at runSequence (D:\ej2-es-build\node_modules\gulp4-run-sequence\index.js:58:31)
>     at Gulp.<anonymous> (D:\ej2-es-build\src\base.js:8:5)
>     at module.exports (D:\ej2-es-build\node_modules\orchestrator\lib\runTask.js:34:7)
>     at Gulp.Orchestrator._runTask (D:\ej2-es-build\node_modules\orchestrator\index.js:273:3)
>     at Gulp.Orchestrator._runStep (D:\ej2-es-build\node_modules\orchestrator\index.js:214:10)
>     at Gulp.Orchestrator.start (D:\ej2-es-build\node_modules\orchestrator\index.js:134:8)
>     at C:\Users\KumaresanSubramani\AppData\Roaming\nvm\v10.15.1\node_modules\gulp\node_modules\gulp-cli\lib\versioned\^3.7.0\index.js:72:20
>     at process._tickCallback (internal/process/next_tick.js:61:11)
> 
> D:\ej2-es-build>

## gulp task

```
gulp.task('buildw', function(done) {
    var runSequence = require('gulp4-run-sequence').use(gulp);
    runSequence('clone', 'topo-sort');
});
```

**Comment by e2tha-e** [comment]
Hi @kumaresan-subramani !

A brief glance at the stack trace tells me your build depends on `Orchestrator`. This is a dependency of `gulp 3`, not `gulp 4`. Somewhere you are requiring the old incompatible `gulp`, and then submitting it to `gulp4-run-sequence` via `.use()`.

Hope this helps!
